/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Roboto } from "next/font/google"
import "./globals.css";

const roboto_init = Roboto({
  subsets : ['latin'] ,
  weight : ['900' , '400'] ,
  variable : '--font-roboto' ,
}) 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NexonDev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={roboto_init.variable}
      >
        {children}
      </body>
    </html>
  );
}
